services:
  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog_dev
    restart: unless-stopped
    ports:
      - "${MAILHOG_SMTP_PORT:-1025}:1025"
      - "${MAILHOG_WEB_PORT:-8025}:8025"
    networks:
      - mailhog_network

volumes: {}

networks:
  mailhog_network:
    name: mailhog_dev_network
    driver: bridge
